### ISSUE TITLE
Can't compile/edit plugin

### ISSUE THREAD

**Issue by sarhatabaot** [vk2gpz/MineResetLite#1]
When trying to edit the project locally, I'm missing `com.vk2gpz.vklib` and `com.vk2gpz.mineresetlite`.

**Comment by vk2gpz** [comment]
I had to implement many of my implementation outside of MineResetLite because when I contacted the author of MineResetLite for including my implementation in MineResetLite, the requested not to and make my own.  

I understood that the dev did not want my code to be part of his code.  Hence, I provided my implementation outside of the MineResetLite and minimise the modification to MineResetLite as much as possible.
